apiVersion: v1
kind: Secret
metadata:
  name: qdrant-api-keys
  namespace: qdrant-system
  labels:
    app: qdrant
type: Opaque
data:
  # These will be base64 encoded API keys
  # Generated during deployment by the auth manager
  api_key: ""
  read_only_api_key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: qdrant-auth-config
  namespace: qdrant-system
  labels:
    app: qdrant-auth-proxy
type: Opaque
data:
  # JWT signing key and configuration
  jwt_secret: ""
  auth_config: ""