---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qdrant-storage
  namespace: qdrant-system
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
---
# for vector Db with very large collections and very heavy loads, SLA 99.999%
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qdrant-storage-premium
  namespace: qdrant-system
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: io2
  iops: "16000"                 # set based on your workload (100 IOPS per GiB, up to 256,000 with io2 Block Express)
  throughput: "1000"            # MiB/s (only supported with Block Express)
